appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c329eef302eb707003bfd1a
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: HNuJpEDo2OYw9WIxqBztSP3ThaWfA9Su8MlXh/OjXPtqbisFiey7jF/A+t6zujj7kjj5VG9QPKp5oew+TUgIPRWaTZVE3EHyVFEUJsmyGlPHmCjYtH5wRMDn7aaVhLnYhd0e3zxUQORWlpVOJ34NfgQVhPnIj6l2RMUcUk6eovnW7egbMw6vwgxGsjW/5RE2A20Q6ryEvbca3wcyTQ8WcqBVY8Xtb3ZkqFmvPiqCieb/VoVswGyzxwLkQWvMYaeDc4oJ6K6l+O4sCXajOHsONVP3fVJ3NtSr1wdn93exCBLoGKKCAMbxZePRcAugyFjVDkGtmOkCzHJCAp+a6AvVE7UYp85PVXnW+GoCvDaOiL8WCPS159wRA1nZcFlyxjT8l3t8auxAsYqFN5GusOS2PG+BWZU2TxIFsYrtM5IaDowxcjcB74FNWAZ7fWQapWTPPIs67fyT6K58kgRitPKughVLFXxKOBRKiuEnihtdZoBvprmlJms/fG4YMBG645ErOZJNjSeCL6XlcgHqK3XwSCXj12MhoOGC570ofvzke3yUOXqhKGe0By282SZV264zrIoKiEElwVBdDOClqQ6zjGaDwA8NEGGUDNgUpPu/cBNKPT94X6I6SA9lIqH+fUDTaAO3wUZQGzBLSL8iaeVmNvWK0NduzKmBCFgekyaxYWU=}
